version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
    - package:
        # Need this to force CircleCI to build on tags since they are ignored by default
        filters:
          tags:
            only: /.*/
          # Branches are automatically included
    # Only runs on branches, not on tags
    - pypi-test:
        requires:
        - package
    # Only runs on tags, not on branches
    - pypi:
        requires:
        - package
        filters:
          tags:
            only: /.*/
          # Only publish to pypi on tags, so ignore branches
          branches:
            ignore: /.*/

jobs:
  package:
    docker:
    - image: cimg/python:3.8
    steps:
    - checkout
    - run: pyenv versions
    - run:
        name: Install pyenv versions
        command: pyenv install 3.6.8 && pyenv install 3.7.2
    - run:
        name: Run tox
        command: tox
  pypi-test:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Verify dist with twine
        command: |
          pip install -U pip
          python setup.py sdist bdist_wheel
          pip install twine
          twine check dist/*
  pypi:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Deploy to pypi
        command: |
          pip install -U pip
          python setup.py sdist bdist_wheel
          pip install twine
          twine check dist/*
          twine upload -u "__token__" dist/*
